In [2]:
import pandas as pd
df=pd.read_csv('data/merge.csv',encoding="shift-jis")
df.head()

   Unnamed: 0             datetime 曜日    局  視聴率（世帯）  視聴率（個人）  視聴数（世帯）  視聴数（個人）
0           0  2017-01-01 05:00:00  日  HUT     12.8      5.3     2349     2150
1           1  2017-01-01 05:01:00  日  HUT     12.8      5.3     2349     2150
2           2  2017-01-01 05:02:00  日  HUT     12.5      5.2     2294     2109
3           3  2017-01-01 05:03:00  日  HUT     12.5      5.1     2294     2069
4           4  2017-01-01 05:04:00  日  HUT     12.7      5.3     2331     2150

In [4]:
df["datetime"]=pd.to_datetime(df.datetime)

In [52]:
newdf=df.loc[df["datetime"].dt.hour.isin([19,20,21,22])&df["datetime"].dt.minute.isin([0,10,20,30,40,50])]
newdf

,Unnamed: 0,datetime,曜日,局,視聴率（世帯）,視聴率（個人）,視聴数（世帯）,視聴数（個人）
840,840,2017-01-01 19:00:00,日,HUT,56.9,38.6,10442,15657
850,850,2017-01-01 19:10:00,日,HUT,57.7,39.7,10589,16103
860,860,2017-01-01 19:20:00,日,HUT,58.6,40.5,10754,16428
870,870,2017-01-01 19:30:00,日,HUT,57.9,40.4,10626,16387
880,880,2017-01-01 19:40:00,日,HUT,58.1,41.2,10663,16712
...,...,...,...,...,...,...,...,...
14190790,12550,2019-12-31 22:10:00,火,ETC,4.8,2.1,914,862
14190800,12560,2019-12-31 22:20:00,火,ETC,4.4,1.7,838,698
14190810,12570,2019-12-31 22:30:00,火,ETC,3.9,1.4,743,574
14190820,12580,2019-12-31 22:40:00,火,ETC,4.1,1.6,781,656
14190830,12590,2019-12-31 22:50:00,火,ETC,3.0,1.0,571,410

In [31]:
newdf=newdf.drop(columns='Unnamed: 0')
newdf=newdf.reset_index(drop=True)
newdf

                  datetime 曜日    局  視聴率（世帯）  視聴率（個人）  視聴数（世帯）  視聴数（個人）
0      2017-01-01 19:00:00  日  HUT     56.9     38.6    10442    15657
1      2017-01-01 19:10:00  日  HUT     57.7     39.7    10589    16103
2      2017-01-01 19:20:00  日  HUT     58.6     40.5    10754    16428
3      2017-01-01 19:30:00  日  HUT     57.9     40.4    10626    16387
4      2017-01-01 19:40:00  日  HUT     58.1     41.2    10663    16712
...                    ... ..  ...      ...      ...      ...      ...
236515 2019-12-31 22:10:00  火  ETC      4.8      2.1      914      862
236516 2019-12-31 22:20:00  火  ETC      4.4      1.7      838      698
236517 2019-12-31 22:30:00  火  ETC      3.9      1.4      743      574
236518 2019-12-31 22:40:00  火  ETC      4.1      1.6      781      656
236519 2019-12-31 22:50:00  火  ETC      3.0      1.0      571      410

[236520 rows x 7 columns]

In [43]:
newdf["timestamp"]=newdf.datetime.astype('int64') // 10**9
newdf

,datetime,曜日,局,視聴率（世帯）,視聴率（個人）,視聴数（世帯）,視聴数（個人）,timestamp
0,2017-01-01 19:00:00,日,HUT,56.9,38.6,10442,15657,1483297200
1,2017-01-01 19:10:00,日,HUT,57.7,39.7,10589,16103,1483297800
2,2017-01-01 19:20:00,日,HUT,58.6,40.5,10754,16428,1483298400
3,2017-01-01 19:30:00,日,HUT,57.9,40.4,10626,16387,1483299000
4,2017-01-01 19:40:00,日,HUT,58.1,41.2,10663,16712,1483299600
...,...,...,...,...,...,...,...,...
236515,2019-12-31 22:10:00,火,ETC,4.8,2.1,914,862,1577830200
236516,2019-12-31 22:20:00,火,ETC,4.4,1.7,838,698,1577830800
236517,2019-12-31 22:30:00,火,ETC,3.9,1.4,743,574,1577831400
236518,2019-12-31 22:40:00,火,ETC,4.1,1.6,781,656,1577832000
236519,2019-12-31 22:50:00,火,ETC,3.0,1.0,571,410,1577832600

In [44]:
newdf.to_csv('data/gp_each10min.csv', encoding="shift_jis")

In [46]:
#以下は番組データを再整理

import pandas as pd
dfb=pd.read_csv('data/2019a.csv',encoding="shift-jis")
dfb.head()

,datetime,曜日,局,年,月,日,開始時,開始分,放送分数,番組分類コード,新番組コード,占拠率（世帯）,メインタイトル,サブタイトル
0,2017-01-01 05:00:00,日,NTV,2017,1,1,5,0,30,190,,2.2,日本で一番早いお笑いバトル！フットンダ王決定戦２０１７,
1,2017-01-01 05:30:00,日,NTV,2017,1,1,5,30,150,072,,5.1,年に一度の新春シューイチネンイチＺＩＰ！＆ズムサタ豪華イチづ,第１部
2,2017-01-01 08:00:00,日,NTV,2017,1,1,8,0,90,072,,6.6,年に一度の新春シューイチネンイチＺＩＰ！＆ズムサタ豪華イチづ,第２部
3,2017-01-01 09:30:00,日,NTV,2017,1,1,9,30,150,190,,9.4,新春しゃべくり００７ ６時間半ＳＰ！,第１部
4,2017-01-01 12:00:00,日,NTV,2017,1,1,12,0,230,190,,10.0,新春しゃべくり００７ ６時間半ＳＰ！,第２部

In [59]:
newdfb=dfb.loc[dfb["開始時"].isin([18,19,20,21,22])]
newdfb["datetime"]=pd.to_datetime(newdfb.datetime)
newdfb=newdfb.reset_index(drop=True)
newdfb

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,datetime,曜日,局,年,月,日,開始時,開始分,放送分数,番組分類コード,新番組コード,占拠率（世帯）,メインタイトル,サブタイトル
0,2017-01-01 18:00:00,日,NTV,2017,1,1,18,0,60,190,,14.2,元日はＴＯＫＩＯ×嵐ウルトラマンＤＡＳＨ,第１部
1,2017-01-01 19:00:00,日,NTV,2017,1,1,19,0,120,190,,14.3,元日はＴＯＫＩＯ×嵐ウルトラマンＤＡＳＨ,第２部
2,2017-01-01 21:00:00,日,NTV,2017,1,1,21,0,135,190,,13.2,嵐にしやがれ元日ＳＰ,
3,2017-01-01 18:00:00,日,TBS,2017,1,1,18,0,60,170,,6.1,究極の男は誰だ！？最強スポーツ男子元日頂上決戦！,
4,2017-01-01 19:00:00,日,TBS,2017,1,1,19,0,120,170,,7.3,究極の男は誰だ！？最強スポーツ男子元日頂上決戦！,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58344,2019-12-31 19:05:00,火,NHK2,2019,12,31,19,5,45,030,,0.2,ドキュランドへようこそ,
58345,2019-12-31 19:50:00,火,NHK2,2019,12,31,19,50,5,20M,,0.2,びじゅチューン！,
58346,2019-12-31 19:55:00,火,NHK2,2019,12,31,19,55,5,010,,0.1,ＮＨＫ手話ニュース,
58347,2019-12-31 20:00:00,火,NHK2,2019,12,31,20,0,80,140,,0.7,Ｎ響第９演奏会,
58348,2019-12-31 21:20:00,火,NHK2,2019,12,31,21,20,145,150,,0.4,クラシック名演・名舞台２０１９,

In [81]:
import datetime

endtime=[]

for index,row in newdfb.iterrows():
 
    et=row["datetime"]+datetime.timedelta(minutes=int(row["放送分数"]))
    endtime.append(et)
    
newdfb["endtime"]=endtime
newdfb

,datetime,曜日,局,年,月,日,開始時,開始分,放送分数,番組分類コード,新番組コード,占拠率（世帯）,メインタイトル,サブタイトル,endtime
0,2017-01-01 18:00:00,日,NTV,2017,1,1,18,0,60,190,,14.2,元日はＴＯＫＩＯ×嵐ウルトラマンＤＡＳＨ,第１部,2017-01-01 19:00:00
1,2017-01-01 19:00:00,日,NTV,2017,1,1,19,0,120,190,,14.3,元日はＴＯＫＩＯ×嵐ウルトラマンＤＡＳＨ,第２部,2017-01-01 21:00:00
2,2017-01-01 21:00:00,日,NTV,2017,1,1,21,0,135,190,,13.2,嵐にしやがれ元日ＳＰ,,2017-01-01 23:15:00
3,2017-01-01 18:00:00,日,TBS,2017,1,1,18,0,60,170,,6.1,究極の男は誰だ！？最強スポーツ男子元日頂上決戦！,,2017-01-01 19:00:00
4,2017-01-01 19:00:00,日,TBS,2017,1,1,19,0,120,170,,7.3,究極の男は誰だ！？最強スポーツ男子元日頂上決戦！,,2017-01-01 21:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58344,2019-12-31 19:05:00,火,NHK2,2019,12,31,19,5,45,030,,0.2,ドキュランドへようこそ,,2019-12-31 19:50:00
58345,2019-12-31 19:50:00,火,NHK2,2019,12,31,19,50,5,20M,,0.2,びじゅチューン！,,2019-12-31 19:55:00
58346,2019-12-31 19:55:00,火,NHK2,2019,12,31,19,55,5,010,,0.1,ＮＨＫ手話ニュース,,2019-12-31 20:00:00
58347,2019-12-31 20:00:00,火,NHK2,2019,12,31,20,0,80,140,,0.7,Ｎ響第９演奏会,,2019-12-31 21:20:00
58348,2019-12-31 21:20:00,火,NHK2,2019,12,31,21,20,145,150,,0.4,クラシック名演・名舞台２０１９,,2019-12-31 23:45:00

In [83]:
newdfb["datetimets"]=newdfb.datetime.astype('int64') // 10**9
newdfb["endtimets"]=newdfb.endtime.astype('int64') // 10**9


newdfb

,datetime,曜日,局,年,月,日,開始時,開始分,放送分数,番組分類コード,新番組コード,占拠率（世帯）,メインタイトル,サブタイトル,endtime,datetimets,endtimets
0,2017-01-01 18:00:00,日,NTV,2017,1,1,18,0,60,190,,14.2,元日はＴＯＫＩＯ×嵐ウルトラマンＤＡＳＨ,第１部,2017-01-01 19:00:00,1483293600,1483297200
1,2017-01-01 19:00:00,日,NTV,2017,1,1,19,0,120,190,,14.3,元日はＴＯＫＩＯ×嵐ウルトラマンＤＡＳＨ,第２部,2017-01-01 21:00:00,1483297200,1483304400
2,2017-01-01 21:00:00,日,NTV,2017,1,1,21,0,135,190,,13.2,嵐にしやがれ元日ＳＰ,,2017-01-01 23:15:00,1483304400,1483312500
3,2017-01-01 18:00:00,日,TBS,2017,1,1,18,0,60,170,,6.1,究極の男は誰だ！？最強スポーツ男子元日頂上決戦！,,2017-01-01 19:00:00,1483293600,1483297200
4,2017-01-01 19:00:00,日,TBS,2017,1,1,19,0,120,170,,7.3,究極の男は誰だ！？最強スポーツ男子元日頂上決戦！,,2017-01-01 21:00:00,1483297200,1483304400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58344,2019-12-31 19:05:00,火,NHK2,2019,12,31,19,5,45,030,,0.2,ドキュランドへようこそ,,2019-12-31 19:50:00,1577819100,1577821800
58345,2019-12-31 19:50:00,火,NHK2,2019,12,31,19,50,5,20M,,0.2,びじゅチューン！,,2019-12-31 19:55:00,1577821800,1577822100
58346,2019-12-31 19:55:00,火,NHK2,2019,12,31,19,55,5,010,,0.1,ＮＨＫ手話ニュース,,2019-12-31 20:00:00,1577822100,1577822400
58347,2019-12-31 20:00:00,火,NHK2,2019,12,31,20,0,80,140,,0.7,Ｎ響第９演奏会,,2019-12-31 21:20:00,1577822400,1577827200
58348,2019-12-31 21:20:00,火,NHK2,2019,12,31,21,20,145,150,,0.4,クラシック名演・名舞台２０１９,,2019-12-31 23:45:00,1577827200,1577835900